module.exports = [
  "ASSURANCE",
  "CYBERSECURITY",
  "INFINITY",
  "SAMPLING",
  "MORNING",
  "EXAMINATION",
  "MASTER",
  "SYSTEM",
  "VISUAL STUDIO",
  "BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY",
];
